name: 'Terraform'
run-name: Infra Deploy of ${{inputs.devops_tf_verb}}

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      devops_tf_verb:
        description: 'Terraform apply/plan/destroy'
        required: true
        default: 'plan'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init
      env:
        TF_VAR_HMAC_ACCESS_KEY: ${{ secrets.HMAC_ACCESS_KEY }}
        TF_VAR_HMAC_SECRET: ${{ secrets.HMAC_SECRET }} 

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve